language: python
python:
  - "2.7"
# safelist
branches:
  only:
  - master
# install dependencies
install:
  - npm install
  - easy_install distribute
  - pip install -r requirements.txt
# run tests
script:
  - echo skip tests
# deploy via aws codedeploy
deploy:
- provider: codedeploy
  revision_type: github
  access_key_id: AKIAI2BWTZAGQ3FQPAHQ
  application: ourrevolution
  deployment_group: QA
  region: us-west-2
