language: python
python:
  - "2.7"
# run off master branch only
branches:
  only:
  - master
# install dependencies
install:
  - npm install
  - easy_install distribute
  - pip install -r requirements.txt
# run tests
script:
  - echo skip tests
# deploy via aws codedeploy
deploy:
- provider: codedeploy
  revision_type: github
  access_key_id: AKIAI2BWTZAGQ3FQPAHQ
  secret_access_key:
    secure: T8Hcmbd/PHLIpELCqpg4wkw+aLkQEsb8bY9xJJzXM6fAex5XK1mFFqp1Cl3oktwU69yw1hmb3FVVIu7sAbbgDB+mfprMPpwPqwEx19+6yDLcElvTi0u6a7Qb22nozVND+2T3JKQQUmR8HrRjrNfa0rFIK2s1e3kNuJIRmhIrUQX3YT32oYIwUstG6jaV5hUTkaA5uyXHJ87ycxHgRomk6YR/GW7z78wiZ8iL7yXrVMUlQMMKHSF++afazAIxbMTmbc9g5Vra0SZH7AyhTO9nTFoPu+6hu0XZW54gP6SQtnhCUQRejTGNC7l3ofQpmLPYoVczAuoEEXShKP46J5DGKTdqCocGGBG2yPafvsIVErxG2z5YSpYrxy4qeI5TkzTjQj31Q3C3i0uvFK7zdqcnS2Hf/xCMz2NBj6MslqCXc5OE4gz5S0t5IzOtL7P5LpGqCZBcI0FWriO4eCc4IYf/bLhYQDE1rj45JkzzCPf+K+Js1Wndo+KWrd6YmRODi/oz+r7+WhaI9nLTuQRgbHWvjKkV3DxeaQvVS1zcUnYkkNgpKLGlbWobeklGG8EHjKyDbDQToJPRCykKpMVRWlM1nv+waheW5KFri84/jINrVNpab+Wq1JCxzAUMs5yIKjH0TGIr4LT2MNnlj0/qxXpfUZ6VA8VI5Zd1hFNpijMpNrw=
  application: ourrevolution
  deployment_group: QA
  region: us-west-2
- provider: codedeploy
  revision_type: github
  access_key_id: AKIAI2BWTZAGQ3FQPAHQ
  secret_access_key:
    secure: T8Hcmbd/PHLIpELCqpg4wkw+aLkQEsb8bY9xJJzXM6fAex5XK1mFFqp1Cl3oktwU69yw1hmb3FVVIu7sAbbgDB+mfprMPpwPqwEx19+6yDLcElvTi0u6a7Qb22nozVND+2T3JKQQUmR8HrRjrNfa0rFIK2s1e3kNuJIRmhIrUQX3YT32oYIwUstG6jaV5hUTkaA5uyXHJ87ycxHgRomk6YR/GW7z78wiZ8iL7yXrVMUlQMMKHSF++afazAIxbMTmbc9g5Vra0SZH7AyhTO9nTFoPu+6hu0XZW54gP6SQtnhCUQRejTGNC7l3ofQpmLPYoVczAuoEEXShKP46J5DGKTdqCocGGBG2yPafvsIVErxG2z5YSpYrxy4qeI5TkzTjQj31Q3C3i0uvFK7zdqcnS2Hf/xCMz2NBj6MslqCXc5OE4gz5S0t5IzOtL7P5LpGqCZBcI0FWriO4eCc4IYf/bLhYQDE1rj45JkzzCPf+K+Js1Wndo+KWrd6YmRODi/oz+r7+WhaI9nLTuQRgbHWvjKkV3DxeaQvVS1zcUnYkkNgpKLGlbWobeklGG8EHjKyDbDQToJPRCykKpMVRWlM1nv+waheW5KFri84/jINrVNpab+Wq1JCxzAUMs5yIKjH0TGIr4LT2MNnlj0/qxXpfUZ6VA8VI5Zd1hFNpijMpNrw=
  application: ourrev-tasks
  deployment_group: QA
  region: us-west-2
